name: Manual
on:
  workflow_dispatch:
    inputos:
      greeting:
        type: string
        default: Hello
        required: ture
        description: A cheerful word
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"